from __future__ import annotations

import copy
from dataclasses import dataclass, field
from typing import Any


@dataclass
class AgentState:
    """
    Shared workflow state passed between all agents.

    Every agent receives the same AgentState instance,
    updates only the fields it owns, and forwards it to
    the next agent in the workflow.
    """

    # ==========================================================
    # Patient Information
    # ==========================================================
    patient: dict[str, Any] = field(default_factory=dict)

    patient_history: dict[str, Any] = field(default_factory=dict)

    symptoms: list[str] = field(default_factory=list)

    medications: list[str] = field(default_factory=list)

    allergies: list[str] = field(default_factory=list)

    # ==========================================================
    # Medical Reports
    # ==========================================================
    uploaded_reports: list[str] = field(default_factory=list)

    report_text: str = ""

    ocr_result: dict[str, Any] = field(default_factory=dict)

    extracted_metrics: dict[str, Any] = field(default_factory=dict)

    # ==========================================================
    # AI Agent Outputs
    # ==========================================================
    disease_risk: dict[str, Any] = field(default_factory=dict)

    knowledge_results: list[dict[str, Any]] = field(default_factory=list)

    drug_analysis: dict[str, Any] = field(default_factory=dict)

    recommendations: list[dict[str, Any]] = field(default_factory=list)

    final_report: dict[str, Any] = field(default_factory=dict)

    # ==========================================================
    # Supervisor Tracking
    # ==========================================================
    agent_outputs: dict[str, Any] = field(default_factory=dict)

    agent_confidence: dict[str, float] = field(default_factory=dict)

    execution_times: dict[str, float] = field(default_factory=dict)

    execution_trace: list[str] = field(default_factory=list)

    # ==========================================================
    # Runtime Status
    # ==========================================================
    metadata: dict[str, Any] = field(default_factory=dict)

    workflow_summary: dict[str, Any] = field(default_factory=dict)

    warnings: list[str] = field(default_factory=list)

    errors: list[str] = field(default_factory=list)

    # ==========================================================
    # Helper Methods
    # ==========================================================
    def add_trace(self, message: str) -> None:
        """Append a workflow execution trace message."""
        self.execution_trace.append(message)

    def add_warning(self, warning: str) -> None:
        """Record a warning generated by an agent."""
        self.warnings.append(warning)

    def add_error(self, error: str) -> None:
        """Record an error generated by an agent."""
        self.errors.append(error)

    def set_agent_output(
        self,
        agent_name: str,
        output: Any,
        confidence: float | None = None,
        execution_time: float | None = None,
    ) -> None:
        """
        Store an agent's output and optional metadata.
        """

        self.agent_outputs[agent_name] = output

        if confidence is not None:
            self.agent_confidence[agent_name] = confidence

        if execution_time is not None:
            self.execution_times[agent_name] = execution_time

    def get_agent_output(self, agent_name: str) -> Any:
        """
        Retrieve a previously stored agent output.
        """

        return self.agent_outputs.get(agent_name)

    def has_errors(self) -> bool:
        """Return True if any errors have been recorded."""
        return len(self.errors) > 0

    def has_warnings(self) -> bool:
        """Return True if any warnings have been recorded."""
        return len(self.warnings) > 0

    def clear_runtime(self) -> None:
        """
        Clear runtime information before a new workflow execution.
        """

        self.execution_trace.clear()
        self.agent_outputs.clear()
        self.agent_confidence.clear()
        self.execution_times.clear()
        self.errors.clear()
        self.warnings.clear()
        self.workflow_summary.clear()

    def mark_workflow_completed(self, status: str = "completed") -> None:
        """Record completion metadata for the supervisor workflow."""
        self.metadata["workflow_completed"] = True
        self.metadata["workflow_status"] = status
        self.metadata.setdefault("workflow_step_count", len(self.execution_trace))

    def record_agent_result(
        self,
        agent_name: str,
        output: Any,
        confidence: float | None = None,
        execution_time: float | None = None,
    ) -> None:
        """Store a normalized agent result and update summary metadata."""
        self.set_agent_output(agent_name, output, confidence=confidence, execution_time=execution_time)
        self.metadata["last_agent"] = agent_name
        self.metadata["last_agent_output"] = copy.deepcopy(output)
        self.metadata["last_agent_confidence"] = confidence
        self.metadata["last_agent_execution_time"] = execution_time

    # Backward-compatible aliases used in older tests/code
    @property
    def patient_context(self) -> dict[str, Any]:
        return self.patient

    @patient_context.setter
    def patient_context(self, value: dict[str, Any]) -> None:
        self.patient = value

    @property
    def raw_report_text(self) -> str:
        return self.report_text

    @raw_report_text.setter
    def raw_report_text(self, value: str) -> None:
        self.report_text = value